### ISSUE TITLE
TypeError: 'map_locsation' is an invalid keyword argument for Unpickler()

### ISSUE THREAD

**Issue by tianke0711** [muzishen/IMAGDressing#10]
Traceback (most recent call last):
  File "inference_IMAGdressing.py", line 156, in <module>
    pipe, generator = prepare(args)
  File "inference_IMAGdressing.py", line 97, in prepare
    model_sd = torch.load(args.model_ckpt, map_locsation="cpu")["module"]
  File "/home/xtian/miniconda3/envs/IMAGDressing/lib/python3.8/site-packages/torch/serialization.py", line 1025, in load
    return _load(opened_zipfile,
  File "/home/xian/miniconda3/envs/IMAGDressing/lib/python3.8/site-packages/torch/serialization.py", line 1444, in _load
    unpickler = UnpicklerWrapper(data_file, **pickle_load_args)
TypeError: 'map_locsation' is an invalid keyword argument for Unpickler()

**Comment by tianke0711** [comment]
it is solved
