### ISSUE TITLE
TypeError: forward() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by tianke0711** [muzishen/IMAGDressing#11]
python inference_IMAGdressing.py --cloth_path /home/ss.tian/IMAGDressing/assets/images/ga
rment/1.jpg

num_channels_latents = self.unet.in_channels
  0%|                                                                                                                               | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "inference_IMAGdressing.py", line 178, in <module>
    output = pipe(
  File "/home/ss.tian/miniconda3/envs/IMAGDressing/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/s.tian/IMAGDressing/dressing_sd/pipelines/IMAGDressing_v1_pipeline.py", line 466, in __call__
    _ = self.reference_unet(
  File "/home/ss.tian/miniconda3/envs/IMAGDressing/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ss.tian/miniconda3/envs/IMAGDressing/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ss.tian/miniconda3/envs/IMAGDressing/lib/python3.8/site-packages/diffusers/models/unets/unet_2d_condition.py", line 1209, in forward
    sample, res_samples = downsample_block(
  File "/home/ss.tian/miniconda3/envs/IMAGDressing/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ss.tian/miniconda3/envs/IMAGDressing/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ss.tian/miniconda3/envs/IMAGDressing/lib/python3.8/site-packages/diffusers/models/unets/unet_2d_blocks.py", line 1288, in forward
    hidden_states = attn(
  File "/home/ss.tian/miniconda3/envs/IMAGDressing/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ss.tian/miniconda3/envs/IMAGDressing/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ss.tian/miniconda3/envs/IMAGDressing/lib/python3.8/site-packages/diffusers/models/transformers/transformer_2d.py", line 442, in forward
    hidden_states = block(
  File "/home/ss.tian/miniconda3/envs/IMAGDressing/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ss.tian/miniconda3/envs/IMAGDressing/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ss.tian/miniconda3/envs/IMAGDressing/lib/python3.8/site-packages/diffusers/models/attention.py", line 453, in forward
    attn_output = self.attn1(
  File "/home/ss.tian/miniconda3/envs/IMAGDressing/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ss.tian/miniconda3/envs/IMAGDressing/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ss.tian/miniconda3/envs/IMAGDressing/lib/python3.8/site-packages/diffusers/models/attention_processor.py", line 559, in forward
    return self.processor(
  File "/home/ss.tian/IMAGDressing/adapter/attention_processor.py", line 60, in __call__
    query = attn.to_q(hidden_states, *args)
  File "/home/ss.tian/miniconda3/envs/IMAGDressing/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ss.tian/miniconda3/envs/IMAGDressing/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given

**Comment by WhiteJiang** [comment]
We did not find your bug after testing. We used diffusers==0.24.0. Is it a problem with the diffusers version? @tianke0711

**Comment by tianke0711** [comment]
> We did not find your bug after testing. We used diffusers==0.24.0. Is it a problem with the diffusers version? @tianke0711

Thanks, it worked
