### ISSUE TITLE
OSError: h94/IP-Adapter does not appear to have a file named image_encoder/config.json. Checkout 'https://huggingface.co/h94/IP-Adapter/main' for available files.

### ISSUE THREAD

**Issue by tianke0711** [muzishen/IMAGDressing#12]
Traceback (most recent call last):
  File "inference_IMAGdressing_controlnetpose.py", line 164, in <module>
    pipe, generator = prepare(args)
  File "inference_IMAGdressing_controlnetpose.py", line 52, in prepare
    image_encoder = CLIPVisionModelWithProjection.from_pretrained("h94/IP-Adapter", subfolder="image_encoder").to(
  File "/home/ss.tian/miniconda3/envs/IMAGDressing/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3122, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(

**Comment by tianke0711** [comment]
python inference_IMAGdressing_controlnetpose.py --cloth_path /home/ss.tian/IMAGDressing/a
ssets/images/garment/2.jpg --pose_path assets/images/pose/1.jpg

**Comment by WhiteJiang** [comment]
> python inference_IMAGdressing_controlnetpose.py --cloth_path /home/ss.tian/IMAGDressing/a ssets/images/garment/2.jpg --pose_path assets/images/pose/1.jpg

This is a bug we left behind and has been fixed in the new version.
