### ISSUE TITLE
Corrupt weight file

### ISSUE THREAD

**Issue by deepkshikha** [muzishen/IMAGDressing#28]
Is uploaded file git clone https://huggingface.co/feishen29/IMAGDressing correct. It seems corrupt getting this error.

`Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/IMAGDressing/inference_IMAGdressing.py", line 154, in <module>
    pipe, generator = prepare(args)
  File "/home/ec2-user/SageMaker/IMAGDressing/inference_IMAGdressing.py", line 97, in prepare
    model_sd = torch.load(args.model_ckpt, map_location="cpu")["module"]
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/torch/serialization.py", line 1114, in load
    return _legacy_load(
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/torch/serialization.py", line 1338, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.`

**Comment by muzishen** [comment]
Thank you for your attention, it seems that your downloaded weights are incomplete

**Comment by KeruZheng** [comment]
Excuse me~ May I ask how did you solve the problem~I met the same problem too as I run the 2 & 3 command.
![image](https://github.com/user-attachments/assets/ff4630af-7951-407d-a90f-8f35dc3f61a8)
